.TH "src/utils/log/ansi_escape_code_def.h" 3 "Toller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/log/ansi_escape_code_def.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOLD_BLUE_FORMAT\fP   '\\x1b[1;34;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_GREEN_FORMAT\fP   '\\x1b[1;32;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_YELLOW_FORMAT\fP   '\\x1b[1;33;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_RED_FORMAT\fP   '\\x1b[1;31;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_CYAN_FORMAT\fP   '\\x1b[1;36;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_FORMAT\fP   '\\x1b[1;39;49m'"
.br
.ti -1c
.RI "#define \fBBOLD_UNDERLINE_FORMAT\fP   '\\x1b[1;4;39;49m'"
.br
.ti -1c
.RI "#define \fBRESET_FORMAT\fP   '\\x1b[0m'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOLD_BLUE_FORMAT   '\\x1b[1;34;49m'"

.PP
Definition at line \fB21\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_CYAN_FORMAT   '\\x1b[1;36;49m'"

.PP
Definition at line \fB25\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_FORMAT   '\\x1b[1;39;49m'"

.PP
Definition at line \fB27\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_GREEN_FORMAT   '\\x1b[1;32;49m'"

.PP
Definition at line \fB22\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_RED_FORMAT   '\\x1b[1;31;49m'"

.PP
Definition at line \fB24\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_UNDERLINE_FORMAT   '\\x1b[1;4;39;49m'"

.PP
Definition at line \fB28\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define BOLD_YELLOW_FORMAT   '\\x1b[1;33;49m'"

.PP
Definition at line \fB23\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SS "#define RESET_FORMAT   '\\x1b[0m'"

.PP
Definition at line \fB30\fP of file \fBansi_escape_code_def\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Toller from the source code\&.
