.TH "src/file_systems/file_systems.c" 3 "Toller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file_systems/file_systems.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include 'file_systems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_toller\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int init_toller ()"

.PP
Definition at line \fB22\fP of file \fBfile_systems\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Toller from the source code\&.
