.TH "src/global_vars/global_vars.h" 3 "Toller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/global_vars/global_vars.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_PATH_LENGTH\fP   4096"
.br
.ti -1c
.RI "#define \fBAPPLICATION_NAME\fP   'Toller'"
.br
.ti -1c
.RI "#define \fBAPPLICATION_NAME_LOWER\fP   'toller'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define APPLICATION_NAME   'Toller'"

.PP
Definition at line \fB22\fP of file \fBglobal_vars\&.h\fP\&.
.SS "#define APPLICATION_NAME_LOWER   'toller'"

.PP
Definition at line \fB23\fP of file \fBglobal_vars\&.h\fP\&.
.SS "#define MAX_PATH_LENGTH   4096"

.PP
Definition at line \fB21\fP of file \fBglobal_vars\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Toller from the source code\&.
